[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
script = "script"
test = "test"
solc = "0.8.25"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[etherscan]
sepolia = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
