on: [push]

name: test

jobs:
  check:
    name: Format check and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run format check
        run: forge fmt --check

      - name: Run tests
        run: forge test -vvv
